<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ArchNet.Features\ArchNet.Features.csproj" />
    <ProjectReference Include="..\..\src\ArchNet.Infrastructure\ArchNet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\ArchNet.Domain\ArchNet.Domain.csproj" />
    <ProjectReference Include="..\..\src\ArchNet.Common\ArchNet.Common.csproj" />
  </ItemGroup>

</Project>
