<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="GraphQL" />
    <PackageReference Include="GraphQL.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArchNet.Domain\ArchNet.Domain.csproj" />
    <ProjectReference Include="..\ArchNet.Common\ArchNet.Common.csproj" />
    <ProjectReference Include="..\ArchNet.Infrastructure\ArchNet.Infrastructure.csproj" />
  </ItemGroup>

</Project>
